[package]
name = "oxinat"
description = "XNAT REST API client"
license = "../LICENSE.md"
repository = "https://github.com/WilkinsonK/xapi-oxidized"
version = "0.3.0"
edition = "2021"

[lib]
name = "oxinat"
path = "src/lib.rs"
crate-type = ["lib"]

[features]
full = ["core", "derive"]
core = []
derive = []

[dependencies]
oxinat_core = { path = "../xnat_core", features = ["derive"] }
oxinat_derive = { path = "../xnat_derive" }
